### ISSUE TITLE
Create build process

### ISSUE THREAD

**Issue by actual-saurabh** [WPWale/wp-hindi-translation-style-guide#17]
(Turn these into distinct issues)

- [x] Add `package.json` (via #18)
- [x] Add gulpfile (via #21)
- [x] Add gulp task for combining src into a single guide (via #21)
- [x] ~~Potentially add gulp task for automated spellcheck~~ (won't work because of the intermixing of Hindi and transliterations of Hindi words in English)
- [x] ~~Integrate build process with Travis CI~~ (doesn't make much sense as of now)
- [x] Potentially convert styleguide to pdf for release & distribution (via #40)
